### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by josephtkim** [nemosfate/prj-rev-bwfs-dasmoto#10]
**Grade: Meets Expectations**

**Summary:** Great job with your first official project in the program! It's no small feat to take a specification image and to build a working webpage from it, so you should be proud! The page design looked great, and I liked that you applied some unique styling to it, such as centering the contents. I also thought your code was cleanly written, and easily readable.

The areas for improvement here are to stay consistent with your code formatting with indentations, wrap sections of the page in div elements to separate them clearly, apply descriptions to sections and alt attributes to img elements, and order the CSS selectors so that it reflects the order of the page, making it easier to follow as you work with it.

As a further challenge, consider adding responsive design to your page. This might take some extra research, but can be a great way to learn and apply important web design concepts. You can take a look at these resources to get started - http://getbootstrap.com/ and https://css-tricks.com/snippets/css/a-guide-to-flexbox/. Based on your work so far, I think you are up for the challenge. Keep up the great work!

**Comment by nemosfate** [comment]
Thankful for the review, I knew afte i submitted the div tags would be on here haha.
