### ISSUE TITLE
Stay consistent with code formatting, such as indentations.

### ISSUE THREAD

**Issue by josephtkim** [nemosfate/prj-rev-bwfs-dasmoto#4]
It's always important to stay consistent with code formatting, and to try and follow best practices for the formatting used. The current standard for indentations is 2 spaces per indent for HTML and CSS. And, you only want to indent element relative to the parent element only, not for other sibling elements. 

Here is how you might apply the formatting to the first section, with div tags added to it

```html
    <div>
      <h2 id="hacksaw">Brushes</h2>
      <img src="./resources/hacksaw.jpeg"/>
      <h3>Hacksaw Brushes</h3>
      <p>Made of the highest quality oak, Hacksaw brushes are known for their weight and ability to hold paint in large amounts.
      <br/> Available in different sizes.
      <br/>
      <span class="boldblue">Starting at $3.00 / brush.</span>
      </p>
    </div>
```

**Comment by nemosfate** [comment]
thank you, i was never 100% on that but this definitely helps.
